# Generated by Django 6.0.1 on 2026-03-29 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quest_images/'),
        ),
    ]
