# Generated by Django 4.2.30 on 2026-04-09 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0005_alter_feedback_id_alter_participation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='quest_images/'),
            preserve_default=False,
        ),
    ]
