# Generated by Django 4.2.30 on 2026-04-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0006_alter_quest_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='queststep',
            options={'ordering': ['order']},
        ),
        migrations.AlterUniqueTogether(
            name='participation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('quest', 'user'), name='unique_participation'),
        ),
        migrations.AddConstraint(
            model_name='queststep',
            constraint=models.UniqueConstraint(fields=('quest', 'order'), name='unique_step_order_per_quest'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_team_membership'),
        ),
    ]
