# Generated by Django 4.2.30 on 2026-04-14 18:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0007_alter_queststep_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
