# Generated by Django 4.2.30 on 2026-04-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0009_alter_teammembership_user'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('participation', 'step'), name='unique_submission_per_step'),
        ),
    ]
