# Generated by Django 4.2.30 on 2026-04-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0010_submission_unique_submission_per_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
