# Generated by Django 6.0.1 on 2026-04-16 04:08

import os
from django.contrib.auth import get_user_model

from django.db import migrations

def create_superuser(apps, schema_editor):
    User = get_user_model()
    username = os.environ.get('DJANGO_SUPERUSER_USERNAME')
    email = os.environ.get('DJANGO_SUPERUSER_EMAIL')
    password = os.environ.get('DJANGO_SUPERUSER_PASSWORD')
    
    if username and email and password:
        if not User.objects.filter(username=username).exists():
            User.objects.create_superuser(username=username, email=email, password=password)
            print(f"Superuser '{username}' created successfully.")
        else:
            print(f"Superuser '{username}' already exists.")


class Migration(migrations.Migration):

    dependencies = [
        ('QuestBoardApp', '0011_team_points'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
