# Generated by Django 6.0.1 on 2026-04-16 04:08

import os
from django.db import migrations
from django.utils import timezone

def create_superuser(apps, schema_editor):
    User = apps.get_model("auth", "User")

    username = os.environ.get("DJANGO_SUPERUSER_USERNAME")
    email = os.environ.get("DJANGO_SUPERUSER_EMAIL")
    password = os.environ.get("DJANGO_SUPERUSER_PASSWORD")

    if not username or not email or not password:
        return

    if User.objects.filter(username=username).exists():
        return

    user = User(
        username=username,
        email=email,
        is_staff=True,
        is_superuser=True,
        is_active=True,
        last_login=timezone.now(),
        date_joined=timezone.now(),
    )
    user.set_password(password)
    user.save()



class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('QuestBoardApp', '0011_team_points'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
