# Generated by Django 6.0.1 on 2026-02-05 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entryDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('streak', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MoodApp.entry')),
                ('title', models.CharField(max_length=50)),
                ('entryText', models.CharField(max_length=500)),
            ],
            bases=('MoodApp.entry',),
        ),
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('entry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='MoodApp.entry')),
                ('mood', models.IntegerField()),
                ('notes', models.CharField(max_length=120)),
            ],
            bases=('MoodApp.entry',),
        ),
    ]
